services:
  - type: web
    name: n8n-supabase
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
    
      #  n8n Core Settings
      
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-supabase.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-supabase.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: 'true'
        
      #  Supabase Database Connection (Transaction Pooler)
      
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-ap-south-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.gybvpuwaumjlgnwvczcr
      - key: DB_POSTGRESDB_PASSWORD
        sync: false 
      - key: DB_POSTGRESDB_SSL
        value: 'true'

      #  Supabase API Keys (optional)
      
      - key: SUPABASE_URL
        value: https://gybvpuwaumjlgnwvczcr.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false